#
#   Copyright (c) 2017-2018 Amit Green.  All rights reserved.
#
AGATE_FILES = ../Agate/RUNME.py

BERYL_FILES = \
    ../Beryl/__init__.py \
    ../Beryl/Ask.py \
    ../Beryl/BerylAnswer.py \
    ../Beryl/Main.py

CRYSTAL_FILES = \
    ../Crystal/__init__.py \
    ../Crystal/Board.py ../Crystal/BlankSquare.py \
    ../Crystal/CardRoot.py ../Crystal/ChessBishop.py ../Crystal/ChessKing.py ../Crystal/ChessKnight.py \
        ../Crystal/ChessPawn.py ../Crystal/ChessRook.py ../Crystal/Core.py \
    ../Crystal/Deck_7.py \
    ../Crystal/FrozenChessCard.py ../Crystal/FrozenCardRoot.py \
    ../Crystal/Game.py \
    ../Crystal/Main.py \
    ../Crystal/Player.py \
    ../Crystal/Square.py \
    ../Crystal/VoidSquare.py

DIAMOND_FILES = \
    ../Diamond/__init__.py \
    ../Diamond/Chore.py ../Diamond/Core.py \
    ../Diamond/Development.py \
    ../Diamond/Fibonacci.py \
    ../Diamond/Interval.py \
    ../Diamond/LifeCycle.py \
    ../Diamond/Main.py \
    ../Diamond/Shared.py ../Diamond/Status.py \
    ../Diamond/Thread.py

GEM_FILES = \
    ../Gem/__init__.py \
    ../Gem/Absent.py ../Gem/All.py ../Gem/Ascii.py \
    ../Gem/Boot.py \
    ../Gem/Cache.py ../Gem/Cache2.py ../Gem/Cadence.py ../Gem/Codec.py ../Gem/ContextManager.py ../Gem/Core.py \
        ../Gem/CatchException.py \
    ../Gem/DelayedFileOutput.py ../Gem/DroveMany.py ../Gem/DumpCache.py \
    ../Gem/ErrorNumber.py ../Gem/Exception.py ../Gem/ExecuteFile.py \
    ../Gem/FileOutput.py ../Gem/FileStatus.py \
    ../Gem/Gaggle.py ../Gem/GarbageCollection.py ../Gem/Global.py \
    ../Gem/Hailstone.py ../Gem/Herd.py ../Gem/Herd_2.py ../Gem/Herd_3.py ../Gem/Herd_4567.py ../Gem/HerdMany.py \
        ../Gem/Horde.py \
    ../Gem/Import.py ../Gem/IO.py \
    ../Gem/LiquidMap.py \
    ../Gem/Map.py ../Gem/Method.py \
    ../Gem/Output.py \
    ../Gem/Path.py ../Gem/PortrayString.py \
    ../Gem/Rabble.py ../Gem/RegularExpression.py \
    ../Gem/Series.py ../Gem/Sequence.py ../Gem/SimpleStringIO.py ../Gem/Sleep.py ../Gem/StringOutput.py ../Gem/System.py \
    ../Gem/Traceback.py ../Gem/Thread.py
    #
    #   Excludes:
    #       ../Gem/GeneratedConjureQuadruple.py
    #

DRAVITE_FILES = \
    ../Dravite/Euclid.py \
    ../Dravite/__init__.py \
    ../Dravite/Main.py \
    ../Dravite/RSA_Example.py

IVORY_FILES = \
    ../Ivory/Main.py

JACINTH_FILES = \
    ../Jacinth/source/link/crystal/Jacinth/Main.java \
    ../Jacinth/source/link/crystal/Jacinth/Shape.java \
    ../Jacinth/source/link/crystal/Mirror/Shape.java \
    ../Jacinth/source/link/crystal/Silver/Inspection.java \
    ../Jacinth/source/link/crystal/Silver/SilverModule.java \
    ../Jacinth/source/link/crystal/Silver/SilverProxy.java \
    ../Jacinth/pom.xml

JASPER_FILES = \
    ../Jasper/Core.py \
    ../Jasper/Main.py \
    ../Jasper/Parse.py ../Jasper/Parse1.py \
        ../Jasper/Pattern.py
    #
    #   Excludes:
    #       ../Jasper/Match.py

LICENSE_FILES = \
    ../OtherLicenses/README.txt

MARBLE_FILES = \
    ../Marble/Core.py \
    ../Marble/NestedConjure.py \
    ../Marble/Main.py

MELANITE_FILES = \
    ../Melanite/Child.py \
    ../Melanite/Core.py \
    ../Melanite/Development.py \
    ../Melanite/Main.py \
    ../Melanite/Multiprocessing.py \

ONYX_FILES = \
    ../Onyx/__init__.py \
    ../Onyx/Core.py \
    ../Onyx/Development.py \
    ../Onyx/ElasticSearch.py \
    ../Onyx/Main.py \

PEARL_FILES = \
    ../Pearl/ActionWord.py ../Pearl/Atom.py \
    ../Pearl/Cache.py ../Pearl/ClassOrder.py ../Pearl/Comment.py ../Pearl/ConjureTreeComment.py ../Pearl/Core.py \
        ../Pearl/CreateMeta.py \
    ../Pearl/Line.py \
    ../Pearl/Method.py \
    ../Pearl/Nub.py \
    ../Pearl/TokenCache.py ../Pearl/Tokenizer.py ../Pearl/Token.py

QUARTZ_FILES = \
    ../Quartz/Parse1.py \
    ../Quartz/Core.py \
    ../Quartz/Main.py \
    ../Quartz/Line.py \
    ../Quartz/Pattern.py \
    #
    #   Excludes:
    #       ../Quartz/Match.py
    #

SAPPHIRE_FILES = \
    ../Sapphire/Atom.py \
    ../Sapphire/BinaryExpression.py ../Sapphire/BookcaseDualExpression.py ../Sapphire/BookcaseDualStatement.py \
        ../Sapphire/BookcaseExpression.py ../Sapphire/BookcaseKeywordStatement.py \
        ../Sapphire/BookcaseKeywordDualStatement.py ../Sapphire/BookcaseManyExpression.py \
        ../Sapphire/BookcaseManyFrill.py ../Sapphire/BookcaseManyStatement.py ../Sapphire/BookcaseStatement.py \
        ../Sapphire/BookcaseTriple.py ../Sapphire/BuildSymbolTable.py \
    ../Sapphire/Cache.py ../Sapphire/CallStatement.py ../Sapphire/ClassOrder.py ../Sapphire/Comment.py \
        ../Sapphire/Combine.py ../Sapphire/Core.py ../Sapphire/CreateMeta.py \
    ../Sapphire/DefinitionHeader.py ../Sapphire/Development.py ../Sapphire/DualFrill.py ../Sapphire/DualStatement.py \
        ../Sapphire/DualToken.py ../Sapphire/DualTwig.py ../Sapphire/DumpToken.py \
    ../Sapphire/Elemental.py \
    ../Sapphire/Indentation.py \
    ../Sapphire/LineMarker.py \
    ../Sapphire/Main.py ../Sapphire/ManyExpression.py ../Sapphire/ManyFrill.py ../Sapphire/MemberExpression.py \
        ../Sapphire/Method.py ../Sapphire/MosiacDefinition.py ../Sapphire/MosiacSymbol.py \
    ../Sapphire/Parse.py \
        ../Sapphire/Parse1.py ../Sapphire/Parse1Atom.py ../Sapphire/Tokenize1Header.py ../Sapphire/Parse1Call.py \
        ../Sapphire/Parse1Complex.py ../Sapphire/Parse1Expression.py ../Sapphire/Parse1ExpressionStatement.py \
        ../Sapphire/Parse1From.py ../Sapphire/Parse1Function.py ../Sapphire/Parse1Import.py \
        ../Sapphire/Parse1Simple.py \
        ../Sapphire/Parse2.py ../Sapphire/Parse3.py \
        ../Sapphire/PostfixExpression.py ../Sapphire/PrefixedDualStatement.py ../Sapphire/Priority.py \
    ../Sapphire/Pattern.py \
    ../Sapphire/QuadrupleFrill.py ../Sapphire/QuadrupleStatement.py ../Sapphire/QuadrupleToken.py \
        ../Sapphire/QuadrupleTwig.py \
    ../Sapphire/Suite.py ../Sapphire/SymbolTable.py \
    ../Sapphire/TernaryExpression.py ../Sapphire/TokenCache.py ../Sapphire/TokenTuple.py \
        ../Sapphire/Tokenize1Atom.py ../Sapphire/Tokenize1Name.py ../Sapphire/Tokenize1Operator.py \
        ../Sapphire/Tree.py ../Sapphire/TripleFrill.py ../Sapphire/TripleStatement.py ../Sapphire/TripleToken.py \
        ../Sapphire/TripleTwig.py ../Sapphire/TupleOfExpression.py \
    ../Sapphire/UnaryExpression.py \
    ../Sapphire/Whitespace.py \
    ../Sapphire/Transform.py \
    ../Sapphire/Variable.py
    #
    #   Excludes:
    #       ../Sapphire/Match.py
    #

TOPAZ_FILES = \
    ../Topaz/CacheSupport.py ../Topaz/ConjureDual.py ../Topaz/ConjureSingle.py ../Topaz/ConjureQuadruple.py \
        ../Topaz/ConjureTriple.py ../Topaz/ConjureTreeComment.py ../Topaz/Core.py \
    ../Topaz/Drove.py \
    ../Topaz/ExceptionChain.py \
    ../Topaz/Herd.py \
    ../Topaz/Main.py \
    ../Topaz/Path.py ../Topaz/Pattern.py ../Topaz/PortrayString.py \
    ../Topaz/Sequence.py ../Topaz/Series.py ../Topaz/StringOutput.py
    #
    #   Excludes:
    #       ../Topaz/GeneratedConjureDual.py
    #       ../Topaz/GeneratedConjureQuadruple.py
    #       ../Topaz/GeneratedConjureTriple.py
    #       ../Topaz/GeneratedNew.py
    #       ../Topaz/OldConjureQuadruple.py
    #

TREMOLITE_FILES = \
    ../Tremolite/Build.py \
    ../Tremolite/Compile.py ../Tremolite/Core.py ../Tremolite/CreateMatch.py \
    ../Tremolite/Main.py \
    ../Tremolite/Name.py \
    ../Tremolite/Parse.py ../Tremolite/PatternWrapper.py \
    #
    #   Excludes:
    #       ../Tremolite/LICENSE
    #       ../Tremolite/Match.py
    #


TREMOLITE_2_FILES = \
    ../Tremolite_2/Core.py \
    ../Tremolite_2/Main.py \
    ../Tremolite_2/Parse.py ../Tremolite_2/Parse1.py \
        ../Tremolite_2/Pattern.py
    #
    #   Excludes:
    #       ../Tremolite_2/Match.py


SARDONYX_FILES = \
    ../Sardonyx/Boot.py

WORK_FILES = \
    Makefile \
    z.java

FILES = \
    $(AGATE_FILES) \
    $(BERYL_FILES) \
    $(CRYSTAL_FILES) \
    $(DIAMOND_FILES) \
    $(DRAVITE_FILES) \
    $(GEM_FILES) \
    $(IVORY_FILES) \
    $(JACINTH_FILES) \
    $(JASPER_FILES) \
    $(LICENSE_FILES) \
    $(MARBLE_FILES) \
    $(MELANITE_FILES) \
    $(ONYX_FILES) \
    $(PEARL_FILES) \
    $(QUARTZ_FILES) \
    $(SAPPHIRE_FILES) \
    $(SARDONYX_FILES) \
    $(TOPAZ_FILES) \
    $(TREMOLITE_2_FILES) \
    $(TREMOLITE_FILES) \
    $(WORK_FILES)


all: clean files links


clean:
	rm -rf __pycache__
	rm -f *.old *.new *.pyc
	rm -f 2re.py 2sf.py 2sp.py 2sc.py
	rm -f 3re.py 3sf.py 3sp.py 3sc.py
	rm -f a.py ab.py ac.py ag.py
	rm -f ba.py bi.py bk.py bm.py bo.py
	rm -f ca.py ca2.py cd.py ce.py cr.py
	rm -f d.py dc.py de.py df.py dfo.py di.py dm.py dr.py dsh.py dst.py dt.py dw.py dy.py
	rm -f ef.py en.py ex.py
	rm -f files fo.py fs.py
	rm -f gcm.py gdc.py gdm.py gdo.py gga.py ggc.py gg4.py gh2.py gh3.py gh4.py ghe.py ghm.py gho.py
	rm -f   gi.py gl.py gq.py gr.py gse.py gsq.py
	rm -f h0p.py
	rm -f   h1p.py h1pa.py h1pc.py h1pe.py h1pes.py h1pf.py h1pi.py h1pm.py h1ps.py h1px.py
	rm -f     h1za.py h1zh.py h1zn.py h1zo.py
	rm -f   h2f.py h2p.py h2ps.py h2s.py h2s.py h2t.py h2w.py
	rm -f   h3e.py h3f.py h3p.py h3s.py h3t.py h3w.py
	rm -f   h4f.py h4s.py h4t.py h4w.py
	rm -f   hat.py hbe.py hby.py hca.py hcb.py hcc.py hcm.py hco.py hcr.py hcs.py hd.py hdh.py hdt.py hel.py
	rm -f   hk.py hkc.py hkd.py hkds.py hkf.py hkk.py hkkd.py hkm.py hkms.py hks.py hkt.py hi.py hl.py
	rm -f   hma.py hma1.py hma2.py hmc.py hmd.py hme.py hmf.py hmo.py hmx.py hmy.py hpr.py hpt.py hs.py
	rm -f   hto.py htr.py htt.py hu.py hv.py hw.py hx.py hy.py
	rm -f in.py im.py io.py iv.py
	rm -f j0p.py j1p.py jb.py jcr.py jm.java jm.xml jma.py jmc.py jms.java jp.py js.java
	rm -f l.txt lr.txt
	rm -f m m.txt m1c.py m1m.py m2c.py m2m.py m3m.py map.py mc.py md.py me.py mm.py mn.py
	rm -f o.py oc.py od.py oe.py om.py
	rm -f pa2.py pat.py path.py paw.py pca.py pcc.py pco.py pcr.py pcm.py pel.py
	rm -f   pj.py pk.py pkc.py pl.py pmo.py pn.py ps.py ps3.py pz.py
	rm -f q1p.py qc.py ql.py qma.py qmc.py qp.py
	rm -f rm.py rx.py
	rm -f sl.py so.py ssio.py sy.py
	rm -f t.java t0p.py t1.py t1p.py t2.py tb.py tcm.py th.py tcr.py tcr1.py tlp.txt
	rm -f   tma.py tma1.py tmc.py tmc1.py tn.py tp.py tp1.py tu.py tw.py tx.py
	rm -f xb.py xf.py
	rm -f vi.java vm.java vm.py vp.java
	rm -f ybd.py ybi.py ybq.py ycb.py ycr.py yd7.py yg.py yki.py ykn.py
	rm -f   ym.py yp.py yq.py yr.py yv.py yw.py yzc.py yzk.py yzr.py
	rm -f zcr.py zcs.py zd.py ze.py zg2.gpy zg2.py zg3.gpy zg3.py zg4.gpy zg4.py
	rm -f   zgn.gpy zgn.py zh.py zj1.py zj2.py zj3.py zj4.py zjtc.py
	rm -f   zm.py zo4.py zpa.py zps.py zpt.py zse.py zso.py zsq.py


files:
	echo $(FILES) >files.new
	mv files.new files


links:
	ln -s /usr/lib/python2.7/re.py                                      2re.py
	ln -s /usr/lib/python2.7/sre_compile.py                             2sc.py
	ln -s /usr/lib/python2.7/sre_constants.py                           2sf.py
	ln -s /usr/lib/python2.7/sre_parse.py                               2sp.py
	ln -s /usr/lib/python3.5/re.py                                      3re.py
	ln -s /usr/lib/python3.5/sre_compile.py                             3sc.py
	ln -s /usr/lib/python3.5/sre_constants.py                           3sf.py
	ln -s /usr/lib/python3.5/sre_parse.py                               3sp.py
	ln -s ../Gem/All.py                                                 a.py
	ln -s ../Gem/Absent.py                                              ab.py
	ln -s ../Gem/Ascii.py                                               ac.py
	ln -s ../Agate/RUNME.py                                             ag.py
	ln -s ../Beryl/BerylAnswer.py                                       ba.py
	ln -s ../Beryl/__init__.py                                          bi.py
	ln -s ../Beryl/Ask.py                                               bk.py
	ln -s ../Beryl/Main.py                                              bm.py
	ln -s ../Gem/Boot.py                                                bo.py
	ln -s ../Gem/Cache.py                                               ca.py
	ln -s ../Gem/Cache2.py                                              ca2.py
	ln -s ../Gem/Cadence.py                                             cd.py
	ln -s ../Gem/CatchException.py                                      ce.py
	ln -s ../Gem/Core.py                                                cr.py
	ln -s ../Diamond/Development.py                                     d.py
	ln -s ../Diamond/Core.py                                            dc.py
	ln -s ../Dravite/Euclid.py                                          de.py
	ln -s ../Diamond/Fibonacci.py                                       df.py
	ln -s ../Gem/DelayedFileOutput.py                                   dfo.py
	ln -s ../Diamond/Interval.py                                        di.py
	ln -s ../Diamond/Main.py                                            dm.py
	ln -s ../Dravite/RSA_Example.py                                     dr.py
	ln -s ../Diamond/Shared.py                                          dsh.py
	ln -s ../Diamond/Status.py                                          dst.py
	ln -s ../Diamond/Thread.py                                          dt.py
	ln -s ../Diamond/Chore.py                                           dw.py
	ln -s ../Diamond/LifeCycle.py                                       dy.py
	ln -s ../Gem/ExecuteFile.py                                         ef.py
	ln -s ../Gem/ErrorNumber.py                                         en.py
	ln -s ../Gem/Exception.py                                           ex.py
	ln -s ../Gem/FileOutput.py                                          fo.py
	ln -s ../Gem/FileStatus.py                                          fs.py
	ln -s ../Gem/ContextManager.py                                      gcm.py
	ln -s ../Gem/DumpCache.py                                           gdc.py
	ln -s ../Gem/DroveMany.py                                           gdm.py
	ln -s ../Gem/Codec.py                                               gdo.py
	ln -s ../Gem/Gaggle.py                                              gga.py
	ln -s ../Gem/GarbageCollection.py                                   ggc.py
	ln -s ../Gem/GeneratedConjureQuadruple.py                           gg4.py
	ln -s ../Gem/Herd_2.py                                              gh2.py
	ln -s ../Gem/Herd_3.py                                              gh3.py
	ln -s ../Gem/Herd_4567.py                                           gh4.py
	ln -s ../Gem/Herd.py                                                ghe.py
	ln -s ../Gem/HerdMany.py                                            ghm.py
	ln -s ../Gem/Horde.py                                               gho.py
	ln -s ../Gem/Hailstone.py                                           gi.py
	ln -s ../Gem/Global.py                                              gl.py
	ln -s ../Gem/LiquidMap.py                                           gq.py
	ln -s ../Gem/Rabble.py                                              gr.py
	ln -s ../Gem/Series.py                                              gse.py
	ln -s ../Gem/Sequence.py                                            gsq.py
	ln -s ../Sapphire/Parse.py                                          h0p.py
	ln -s ../Sapphire/Parse1.py                                         h1p.py
	ln -s ../Sapphire/Parse1Atom.py                                     h1pa.py
	ln -s ../Sapphire/Parse1Call.py                                     h1pc.py
	ln -s ../Sapphire/Parse1Expression.py                               h1pe.py
	ln -s ../Sapphire/Parse1ExpressionStatement.py                      h1pes.py
	ln -s ../Sapphire/Parse1Function.py                                 h1pf.py
	ln -s ../Sapphire/Parse1Import.py                                   h1pi.py
	ln -s ../Sapphire/Parse1From.py                                     h1pm.py
	ln -s ../Sapphire/Parse1Simple.py                                   h1ps.py
	ln -s ../Sapphire/Parse1Complex.py                                  h1px.py
	ln -s ../Sapphire/Tokenize1Atom.py                                  h1za.py
	ln -s ../Sapphire/Tokenize1Header.py                                h1zh.py
	ln -s ../Sapphire/Tokenize1Name.py                                  h1zn.py
	ln -s ../Sapphire/Tokenize1Operator.py                              h1zo.py
	ln -s ../Sapphire/Parse2.py                                         h2p.py
	ln -s ../Sapphire/Parse3.py                                         h3p.py
	ln -s ../Sapphire/DualFrill.py                                      h2f.py
	ln -s ../Sapphire/PrefixedDualStatement.py                          h2ps.py
	ln -s ../Sapphire/DualStatement.py                                  h2s.py
	ln -s ../Sapphire/DualToken.py                                      h2t.py
	ln -s ../Sapphire/DualTwig.py                                       h2w.py
	ln -s ../Sapphire/TernaryExpression.py                              h3e.py
	ln -s ../Sapphire/TripleFrill.py                                    h3f.py
	ln -s ../Sapphire/TripleStatement.py                                h3s.py
	ln -s ../Sapphire/TripleToken.py                                    h3t.py
	ln -s ../Sapphire/TripleTwig.py                                     h3w.py
	ln -s ../Sapphire/QuadrupleFrill.py                                 h4f.py
	ln -s ../Sapphire/QuadrupleStatement.py                             h4s.py
	ln -s ../Sapphire/QuadrupleToken.py                                 h4t.py
	ln -s ../Sapphire/QuadrupleTwig.py                                  h4w.py
	ln -s ../Sapphire/Atom.py                                           hat.py
	ln -s ../Sapphire/BinaryExpression.py                               hbe.py
	ln -s ../Sapphire/BuildSymbolTable.py                               hby.py
	ln -s ../Sapphire/Cache.py                                          hca.py
	ln -s ../Sapphire/Combine.py                                        hcb.py
	ln -s ../Sapphire/CreateMeta.py                                     hcc.py
	ln -s ../Sapphire/Comment.py                                        hcm.py
	ln -s ../Sapphire/ClassOrder.py                                     hco.py
	ln -s ../Sapphire/CallStatement.py                                  hcs.py
	ln -s ../Sapphire/Core.py                                           hcr.py
	ln -s ../Sapphire/Development.py                                    hd.py
	ln -s ../Sapphire/DefinitionHeader.py                               hdh.py
	ln -s ../Sapphire/DumpToken.py                                      hdt.py
	ln -s ../Sapphire/Elemental.py                                      hel.py
	ln -s ../Sapphire/BookcaseExpression.py                             hk.py
	ln -s ../Sapphire/TokenCache.py                                     hkc.py
	ln -s ../Sapphire/BookcaseDualExpression.py                         hkd.py
	ln -s ../Sapphire/BookcaseDualStatement.py                          hkds.py
	ln -s ../Sapphire/BookcaseManyFrill.py                              hkf.py
	ln -s ../Sapphire/BookcaseKeywordStatement.py                       hkk.py
	ln -s ../Sapphire/BookcaseKeywordDualStatement.py                   hkkd.py
	ln -s ../Sapphire/BookcaseManyExpression.py                         hkm.py
	ln -s ../Sapphire/BookcaseManyStatement.py                          hkms.py
	ln -s ../Sapphire/BookcaseStatement.py                              hks.py
	ln -s ../Sapphire/BookcaseTriple.py                                 hkt.py
	ln -s ../Sapphire/Indentation.py                                    hi.py
	ln -s ../Sapphire/LineMarker.py                                     hl.py
	ln -s ../Sapphire/Main.py                                           hma.py
	ln -s ../bin/.pyxie/hma.py                                          hma1.py
	ln -s ../bin/.pyxie/hma2.py                                         hma2.py
	ln -s ../Sapphire/Match.py                                          hmc.py
	ln -s ../Sapphire/MosiacDefinition.py                               hmd.py
	ln -s ../Sapphire/MemberExpression.py                               hme.py
	ln -s ../Sapphire/ManyFrill.py                                      hmf.py
	ln -s ../Sapphire/Method.py                                         hmo.py
	ln -s ../Sapphire/ManyExpression.py                                 hmx.py
	ln -s ../Sapphire/MosiacSymbol.py                                   hmy.py
	ln -s ../Sapphire/Priority.py                                       hpr.py
	ln -s ../Sapphire/Pattern.py                                        hpt.py
	ln -s ../Sapphire/Suite.py                                          hs.py
	ln -s ../Sapphire/TupleOfExpression.py                              hto.py
	ln -s ../Sapphire/Tree.py                                           htr.py
	ln -s ../Sapphire/TokenTuple.py                                     htt.py
	ln -s ../Sapphire/UnaryExpression.py                                hu.py
	ln -s ../Sapphire/Variable.py                                       hv.py
	ln -s ../Sapphire/Whitespace.py                                     hw.py
	ln -s ../Sapphire/PostfixExpression.py                              hx.py
	ln -s ../Sapphire/SymbolTable.py                                    hy.py
	ln -s ../Gem/__init__.py                                            in.py
	ln -s ../Gem/Import.py                                              im.py
	ln -s ../Ivory/Main.py                                              iv.py
	ln -s ../Gem/IO.py                                                  io.py
	ln -s ../Jasper/Parse.py                                            j0p.py
	ln -s ../Jasper/Parse1.py                                           j1p.py
	ln -s ../Junk/Boot.py                                               jb.py
	ln -s ../Jasper/Core.py                                             jcr.py
	ln -s ../Jacinth/source/link/crystal/Jacinth/Main.java              jm.java
	ln -s ../Jacinth/pom.xml                                            jm.xml
	ln -s ../Jasper/Main.py                                             jma.py
	ln -s ../Jasper/Match.py                                            jmc.py
	ln -s ../Jacinth/source/link/crystal/Mirror/Shape.java              jms.java
	ln -s ../Jasper/Pattern.py                                          jp.py
	ln -s ../Jacinth/source/link/crystal/Jacinth/Shape.java             js.java
	ln -s log.txt                                                       l.txt
	ln -s ../OtherLicenses/README.txt                                   lr.txt
	ln -s Makefile                                                      m
	ln -s mine.txt                                                      m.txt
	ln -s ../Marble/Core.py                                             m1c.py
	ln -s ../Marble/Main.py                                             m1m.py
	ln -s ../Melanite/Core.py                                           m2c.py
	ln -s ../Melanite/Main.py                                           m2m.py
	ln -s ../Gem/Map.py                                                 map.py
	ln -s ../Melanite/Child.py                                          mc.py
	ln -s ../Melanite/Development.py                                    md.py
	ln -s ../Gem/Method.py                                              me.py
	ln -s ../Melanite/Multiprocessing.py                                mm.py
	ln -s ../Marble/NestedConjure.py                                    mn.py
	ln -s ../Gem/Output.py                                              o.py
	ln -s ../Onyx/Core.py                                               oc.py
	ln -s ../Onyx/Development.py                                        od.py
	ln -s ../Onyx/ElasticSearch.py                                      oe.py
	ln -s ../Onyx/Main.py                                               om.py
	ln -s ../Gem/Path2.py                                               pa2.py
	ln -s ../Pearl/Atom.py                                              pat.py
	ln -s ../Gem/Path.py                                                path.py
	ln -s ../Pearl/ActionWord.py                                        paw.py
	ln -s ../Pearl/Cache.py                                             pca.py
	ln -s ../Pearl/CreateMeta.py                                        pcc.py
	ln -s ../Pearl/Comment.py                                           pcm.py
	ln -s ../Pearl/ClassOrder.py                                        pco.py
	ln -s ../Pearl/Core.py                                              pcr.py
	ln -s ../Pearl/Elemental.py                                         pel.py
	ln -s ../Pearl/ConjureTreeComment.py                                pj.py
	ln -s ../Pearl/Token.py                                             pk.py
	ln -s ../Pearl/TokenCache.py                                        pkc.py
	ln -s ../Pearl/Line.py                                              pl.py
	ln -s ../Pearl/Method.py                                            pmo.py
	ln -s ../Pearl/Nub.py                                               pn.py
	ln -s ../Gem/PortrayString.py                                       ps.py
	ln -s ../Junk/PortrayString_3.py                                    ps3.py
	ln -s ../Pearl/Tokenizer.py                                         pz.py
	ln -s ../Quartz/Parse1.py                                           q1p.py
	ln -s ../Quartz/Core.py                                             qc.py
	ln -s ../Quartz/Line.py                                             ql.py
	ln -s ../Quartz/Main.py                                             qma.py
	ln -s ../Quartz/Match.py                                            qmc.py
	ln -s ../Quartz/Pattern.py                                          qp.py
	ln -s ../Agate/RUNME.py                                             rm.py
	ln -s ../Gem/RegularExpression.py                                   rx.py
	ln -s ../Gem/Sleep.py                                               sl.py
	ln -s ../Gem/StringOutput.py                                        so.py
	ln -s ../Gem/SimpleStringIO.py                                      ssio.py
	ln -s ../Gem/System.py                                              sy.py
	ln -s test.java                                                     t.java
	ln -s ../Tremolite_2/Parse.py                                       t0p.py
	ln -s test.py                                                       t1.py
	ln -s ../Tremolite_2/Parse1.py                                      t1p.py
	ln -s test2.py                                                      t2.py
	ln -s ../Gem/Traceback.py                                           tb.py
	ln -s ../Tremolite/CreateMatch.py                                   tcm.py
	ln -s ../Tremolite/Core.py                                          tcr.py
	ln -s ../Tremolite_2/Core.py                                        tcr1.py
	ln -s ../Gem/Thread.py                                              th.py
	ln -s ../Tremolite/LicenseTemplate.txt                              tlp.txt
	ln -s ../Tremolite_2/Main.py                                        tma.py
	ln -s ../Tremolite/Main.py                                          tma1.py
	ln -s ../Tremolite_2/Match.py                                       tmc.py
	ln -s ../Tremolite/Match.py                                         tmc1.py
	ln -s ../Tremolite/Name.py                                          tn.py
	ln -s ../Tremolite_2/Pattern.py                                     tp.py
	ln -s ../Tremolite/Parse.py                                         tp1.py
	ln -s ../Tremolite/Build.py                                         tu.py
	ln -s ../Tremolite/PatternWrapper.py                                tw.py
	ln -s ../Tremolite/Compile.py                                       tx.py
	ln -s ../Dravite/Main.py                                            vm.py
	ln -s ../Jacinth/source/link/crystal/Silver/Inspection.java         vi.java
	ln -s ../Jacinth/source/link/crystal/Silver/SilverModule.java       vm.java
	ln -s ../Jacinth/source/link/crystal/Silver/SilverProxy.java        vp.java
	ln -s ../Sardonyx/Boot.py                                           xb.py
	ln -s ../Sapphire/Transform.py                                      xf.py
	ln -s ../Crystal/Board.py                                           ybd.py
	ln -s ../Crystal/ChessBishop.py                                     ybi.py
	ln -s ../Crystal/BlankSquare.py                                     ybq.py
	ln -s ../Crystal/CardRoot.py                                        ycb.py
	ln -s ../Crystal/Core.py                                            ycr.py
	ln -s ../Crystal/Deck_7.py                                          yd7.py
	ln -s ../Crystal/Game.py                                            yg.py
	ln -s ../Crystal/ChessKing.py                                       yki.py
	ln -s ../Crystal/ChessKnight.py                                     ykn.py
	ln -s ../Crystal/Main.py                                            ym.py
	ln -s ../Crystal/Player.py                                          yp.py
	ln -s ../Crystal/Square.py                                          yq.py
	ln -s ../Crystal/ChessRook.py                                       yr.py
	ln -s ../Crystal/VoidSquare.py                                      yv.py
	ln -s ../Crystal/ChessPawn.py                                       yw.py
	ln -s ../Crystal/FrozenChessCard.py                                 yzc.py
	ln -s ../Crystal/FrozenCardRoot.py                                  yzr.py
	ln -s ../Topaz/Core.py                                              zcr.py
	ln -s ../Topaz/CacheSupport.py                                      zcs.py
	ln -s ../Topaz/Drove.py                                             zd.py
	ln -s ../Topaz/ExceptionChain.py                                    ze.py
	ln -s ../Topaz/GeneratedConjureDual.gpy                             zg2.gpy
	ln -s ../Topaz/GeneratedConjureDual.py                              zg2.py
	ln -s ../Topaz/GeneratedConjureTriple.gpy                           zg3.gpy
	ln -s ../Topaz/GeneratedConjureTriple.py                            zg3.py
	ln -s ../Topaz/GeneratedConjureQuadruple.gpy                        zg4.gpy
	ln -s ../Topaz/GeneratedConjureQuadruple.py                         zg4.py
	ln -s ../Topaz/GeneratedNew.gpy                                     zgn.gpy
	ln -s ../Topaz/GeneratedNew.py                                      zgn.py
	ln -s ../Topaz/Herd.py                                              zh.py
	ln -s ../Topaz/ConjureSingle.py                                     zj1.py
	ln -s ../Topaz/ConjureDual.py                                       zj2.py
	ln -s ../Topaz/ConjureTriple.py                                     zj3.py
	ln -s ../Topaz/ConjureQuadruple.py                                  zj4.py
	ln -s ../Topaz/ConjureTreeComment.py                                zjtc.py
	ln -s ../Topaz/Main.py                                              zm.py
	ln -s ../Topaz/OldConjureQuadruple.py                               zo4.py
	ln -s ../Topaz/Path.py                                              zpa.py
	ln -s ../Topaz/PortrayString.py                                     zps.py
	ln -s ../Topaz/Pattern.py                                           zpt.py
	ln -s ../Topaz/Series.py                                            zse.py
	ln -s ../Topaz/StringOutput.py                                      zso.py
	ln -s ../Topaz/Sequence.py                                          zsq.py


wc:
	#
	#  Excludes $(AGATE_FILES)
	#
	wc -l \
        $(BERYL_FILES) \
        $(CRYSTAL_FILES) \
        $(DIAMOND_FILES) \
        $(DRAVITE_FILES) \
        $(GEM_FILES) \
        $(IVORY_FILES) \
        $(JACINTH_FILES) \
        $(JASPER_FILES) \
        $(LICENSE_FILES) \
        $(MARBLE_FILES) \
        $(MELANITE_FILES) \
        $(ONYX_FILES) \
        $(QUARTZ_FILES) \
        $(SAPPHIRE_FILES) \
        $(SARDONYX_FILES) \
        $(TOPAZ_FILES) \
        $(TREMOLITE_FILES) \
        $(TREMOLITE_2_FILES) \
        $(WORK_FILES)

test:
	cat \
        $(BERYL_FILES) \
        $(CRYSTAL_FILES) \
        $(DIAMOND_FILES) \
        $(DRAVITE_FILES) \
        $(GEM_FILES) \
        $(IVORY_FILES) \
        $(JASPER_FILES) \
        $(MELANITE_FILES) \
        $(ONYX_FILES) \
        $(PEARL_FILES) \
        $(QUARTZ_FILES) \
        $(SAPPHIRE_FILES) \
        $(SARDONYX_FILES) \
        $(TOPAZ_FILES) \
        $(TREMOLITE_FILES) \
        $(TREMOLITE_2_FILES) \
            >test.py
	bash run.sh
